name: Automated Preprocessing (Kriteria 1)

on:
  push:
    branches:
      - main
    paths:
      - "namadataset_raw/**"
      - "preprocessing/automate_Nama-siswa.py"
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: preprocessing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Sesuaikan jika script Anda butuh library lain, misal scikit-learn
          pip install pandas scikit-learn

      - name: Run preprocessing script
        run: python automate_Nama-siswa.py

      - name: Commit and push preprocessed data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Pastikan path ke file csv Anda sudah benar
          git add namadataset_preprocessing/mushrooms_preprocessed.csv
          # Commit hanya jika ada perubahan
          git diff --staged --quiet || git commit -m "Automated preprocessing: update preprocessed dataset"
          git push
